config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users, controllers:{
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  namespace :admin do
    resources :banks do
    member do
      get :sub
    end
  end
    resources :users
  end
  resources :accounts do
    member do
      get :approve
      get :find_reciever
    end
    resources :transactions
  end
  root 'home#index' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bank.rb
class Bank < ApplicationRecord
    has_many :accounts
end

app/controllers/admin/banks_controller.rb
module Admin
class BanksController < ApplicationController
    load_and_authorize_resource
    include BankConcern
    def index 
        @banks=Bank.all
    end
    def new 
        @bank=Bank.new
    end
    def create 
        create_bank
    end
    def show 
    end
    def edit 
    end
    def update 
        update_bank
    end 
    def destroy
        @bank.destroy
        redirect_to admin_banks_path
    end
    private
    def bank_params
      params.require(:bank).permit(:title)
    end
end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/admin/banks/_form.html.erb
<div class="form-group">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-4">
        <div class="card">
          <div class="card-body">
<%= form_for @bank, url: path, method: method_type, local: true do |f| %>

    <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@bank.errors.count, "error") %> prohibited
        this bank from being saved:
      </h2>
      <ul>
        <% @bank.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
      <div class="form-label"><%= f.label :title %></div>
      <%= f.text_field :title ,class: 'col-lg-4 form-control'%>
   <br/>
   <div class="btn btn-gray">
      <%= f.submit %>
      </div>
    
    
  <% end %>
</div>  
</div>
</div>
</div>
</div>
</div>

app/views/admin/banks/edit.html.erb
<center><h1>Edit Bank</h1></center>
<%= render 'form' , path: admin_bank_path , method_type: 'put'%>

app/views/admin/banks/index.html.erb
<li>
  <a  href="/admin/banks/new" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
  <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Add New Bank</span> </a>
  </a>
</li>          
<h1>Listing banks</h1>
  
<table id="bank-table-id" class="table">
<thead class="thead-light">
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Actions</th>
  </tr>
 </thead>
 <tbody>
  <% @banks.each do |bank| %>
    <tr>
      <td><%= bank.title %></td>
      <td>
       <button class="btn btn-light"><%= link_to 'Destroy', admin_bank_path(bank), method: :delete, data: { confirm: 'Are you sure?' } %></button>
       
       <button class="btn btn-light"><%= link_to 'Edit', edit_admin_bank_path(bank) %></button>
      
       <button class="btn btn-light"><%= link_to 'Show', admin_bank_path(bank) %></button>
     </td>
      

    </tr>
    <%end%>
 </tbody>
 </thead>
 </table>
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "banking.js" %>
<% end %>

app/views/admin/banks/new.html.erb
<center><h1>New Bank</h1></center>
<%= render 'form' , path: admin_banks_path , method_type: 'POST'%>

app/views/admin/banks/show.html.erb
<div class="form-group">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card">
                <div class="card-body">
<p>
<strong>Name:</strong>
  <%= @bank.title %>
</p>

</div>
</div>
    </div>
    </div>
    </div>
    </div>
<center>
     <%= link_to 'Back', admin_banks_path %>
</center>
<br>

app/views/admin/banks/sub.js.erb
$('#reciever_select').empty().append(`<%=options_from_collection_for_select(@account.all, :account_no, :title, prompt: true)%>`);