config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users, controllers:{
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  namespace :admin do
    resources :banks do
    member do
      get :sub
    end
  end
    resources :users
  end
  resources :accounts do
    member do
      get :approve
      get :find_reciever
    end
    resources :transactions
  end
  root 'home#index' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    load_and_authorize_resource
    include TransactionConcern
    def index
        @account=Account.find(params[:account_id])
        @transactions = Transaction.sent_recieved_transactions(@account)
    end
    def new 
        @transaction=Transaction.new
        @account=Account.find(params[:account_id])
    end
    def create
        @transaction=Transaction.new(transaction_params)
        save_transaction
    end
    def show 
    end
    def destroy
        @transaction.destroy
        redirect_to account_transactions_path(@account)
    end
    private
    def transaction_params
      params.require(:transaction).permit(:sender_account,:reciever_account,:amount,:bank_id,:reciever_title,:user_id,:account_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<div class="form-group">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-4">
        <div class="card">
          <div class="card-body">
<%= form_for @transaction, url: path, method: method_type, local: true do |f| %>

    <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@transaction.errors.count, "error") %> prohibited
        this transaction from being saved:
      </h2>
      <ul>
        <% @transaction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
      <%= f.text_field :sender_account ,class: 'col-lg-4 form-control',
      value: @account.account_no, type: :hidden, id: 'sender'%>
      <%= f.text_field :account_id ,class: 'col-lg-4 form-control',
      value: @account.id, type: :hidden, id: 'account'%>
      <%= f.text_field :user_id ,class: 'col-lg-4 form-control',
      value: current_user.id, type: :hidden%>
   <br/>
   <%@banks=Bank.all%>
   <div class="form-label"><%= f.label :bank %></div>
      <%= f.select :bank_id, options_for_select(@banks.collect { |bank|
    [bank.title.titleize, @bank=bank,bank.id] }, 1), {}, { id: 'bank_select'} %>
 <br />
   
   <%
=begin%>
 <div class="form-label"><%= f.label :reciever_account %></div>
   
 <%= f.select :reciever_account,"", {}, :id => "reciever_select"%>
    <br />  
<%
=end%>
    <div class="form-label"><%= f.label :reciever_account %></div>
      <%= f.text_field :reciever_account ,class: 'col-lg-4 form-control',id: 'reciever'%>
   <br/>
   <div class="form-label"><%= f.label :reciever_name %></div>
      <%= f.text_field :reciever_title ,class: 'col-lg-4 form-control',id: 'reciever_title'%>
   <br/>
   <div class="form-label"><%= f.label :ammount %></div>
      <%= f.text_field :amount ,class: 'col-lg-4 form-control'%>
   <br/>
   <center><div class="btn btn-gray">
      <%= f.submit %>
      </div></center>
    
    
  <% end %>
</div>  
</div>
</div>
</div>
</div>
</div>
<script>
   $('#reciever').on('change', function() {
     var rec = $(this).val();
    $.ajax({
      url: `/accounts/${rec}/find_reciever`,
        type: "get",
        success: function (data) {
          
        }
    });
});
</script>

app/views/transactions/index.html.erb
<h1>Listing Transactions of <%= current_user.firstname%></h1>
  
<table id="transaction-table-id" class="table">
<thead class="thead-light">
  <tr>
    <th scope="col">Sender</th>
    <th scope="col">Reciever</th>
     <th scope="col">Sender's Name</th>
    <th scope="col">Reciever's Name</th>
    <th scope="col">Amount</th>
    <th scope="col">Actions</th>
  </tr>
 </thead>
 <tbody>
  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.sender_account %></td>
      <td><%= transaction.reciever_account %></td>
      <td><%= transaction.account.title%></td>
      <td><%= transaction.reciever_title %></td>
      <td><%= transaction.amount %></td>
     <td>
       <button class="btn btn-light"><%= link_to 'Show', account_transaction_path(@account.id,transaction) %></button>
     </td>
      

    </tr>
    <%end%>
 </tbody>
 </thead>
 </table>
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "banking.js" %>
<% end %>
 

app/views/transactions/new.html.erb
<center><h1>New Transaction</h1></center>
<%= render 'form' , path: account_transactions_path , method_type: 'POST'%>

app/views/transactions/show.html.erb
<div class="form-group">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card">
                <div class="card-body">
<p>
<strong>Sender:</strong>
  <%= @transaction.sender_account %>
</p>
<p>
<strong>Reciever:</strong>
  <%= @transaction.reciever_account %>
</p>
<p>
<strong>Amount:</strong>
  <%= @transaction.amount %>
</p>
</div>
</div>
    </div>
    </div>
    </div>
    </div>
<center>
     <%= link_to 'Back', account_transactions_path(@account) %>
</center>
<br>