config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users, controllers:{
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  namespace :admin do
    resources :banks do
    member do
      get :sub
    end
  end
    resources :users
  end
  resources :accounts do
    member do
      get :approve
      get :find_reciever
    end
    resources :transactions
  end
  root 'home#index' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :bank
  belongs_to :user
  validates :title,presence: :true
  # scope :rich,->{ where('balance >= ?',"500000")}
  has_many :transactions, dependent: :destroy
  before_create :generate_token
  enum account_type: [
    :current,
    :saving
  ]
  enum status: [
    :active,
    :pending
  ]
  after_initialize :set_default_status, :if => :new_record?

  def set_default_status
     self.status ||= :pending
  end
  def generate_token
    self.account_no=SecureRandom.hex(2)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    load_and_authorize_resource
    include AccountsConcern
     def index 
        all_accounts
    end
    def new 
        @account=Account.new
    end
    def create 
        create_account
    end
    def show 
    end
    def edit 
    end
    def update 
        update_account
    end 
    def destroy
        @account.destroy
        redirect_to accounts_path
    end
    private
    def account_params
      params.require(:account).permit(:account_no,:title,:account_type,:status,:balance,:user_id,:bank_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="form-group">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-4">
        <div class="card">
          <div class="card-body">
<%= form_for @account, url: path, method: method_type, local: true do |f| %>

    <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@account.errors.count, "error") %> prohibited
        this account from being saved:
      </h2>
      <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
      <div class="form-label"><%= f.label :title %></div>
      <%= f.text_field :title ,class: 'col-lg-4 form-control'%>
   <br/>
   <div class="form-label"><%= f.label :balance %></div>
      <%= f.text_field :balance ,class: 'col-lg-4 form-control'%>
   <br/>
   <div class="form-label"><%= f.label :bank %></div>
      <%= f.collection_select(:bank_id, Bank.all, :id, :title, prompt: true) %>
      <br />
      <%= f.number_field :user_id,
    value: current_user.id , type: :hidden%>
  <div class="form-label"><%= f.label :account_type %></div>
      <%= f.select :account_type, ['current','saving'], autofocus: true, autocomplete: "account_type",{}=> { class: 'form-control' } %>
      <br />
   <center><div class="btn btn-gray">
      <%= f.submit %>
      </div></center>
    
    
  <% end %>
</div>  
</div>
</div>
</div>
</div>
</div>

app/views/accounts/edit.html.erb
<center><h1>Edit Bank</h1></center>
<%= render 'form' , path: account_path , method_type: 'put'%>

app/views/accounts/find_reciever.js.erb
$('#reciever_title').empty().val(`<%= @rec_name.title %>`);

app/views/accounts/index.html.erb
<h1>Listing Accounts</h1>
  
<table id="account-table-id" class="table">
<thead class="thead-light">
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Account Number</th>
    <th scope="col">Type</th>
    <th scope="col">Balance</th>
    <th scope="col">Holder</th>
    <th scope="col">Bank</th>
    <th scope="col">Status</th>
    <th scope="col">Actions</th>
  </tr>
 </thead>
 <tbody>
  <% @accounts.each do |account| %>
    <tr>
      <td><%= account.title %></td>
      <td><%= account.account_no %></td>
      <td><%= account.account_type %></td>
      <td><%= account.balance %></td>
      <td><%= account.user.firstname %></td>
      <td><%= account.bank.title %></td>
      <td><%= account.status %></td>
      <td>
      <%if account.status=="active" && current_user.user?%>
      <button class="btn btn-light"><%= link_to 'New Transaction', new_account_transaction_path(account) %></button>
      <%end%>
      <button class="btn btn-light"><%= link_to 'All Transaction', account_transactions_path(account) %></button>
      
       <button class="btn btn-light"><%= link_to 'Destroy', account_path(account), method: :delete, data: { confirm: 'Are you sure?' } %></button>
       
       <button class="btn btn-light"><%= link_to 'Edit', edit_account_path(account) %></button>
      
       <button class="btn btn-light"><%= link_to 'Show', account_path(account) %></button>
      <%if current_user.admin? && account.status=="pending"%>
       <button class="btn btn-light"><%= link_to 'Approve', approve_account_path(account) %></button>
      <%end%>
     </td>
      

    </tr>
    <%end%>
 </tbody>
 </thead>
 </table>
 <% content_for :javascript_includes do %>
  <%= javascript_include_tag "banking.js" %>
<% end %>

app/views/accounts/new.html.erb
<center><h1>New Account</h1></center>
<%= render 'form' , path: accounts_path , method_type: 'POST'%>

app/views/accounts/show.html.erb
<div class="form-group">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card">
                <div class="card-body">
<p>
<strong>Name:</strong>
  <%= @account.title %>
</p>
<p>
<strong>Balance:</strong>
  <%= @account.balance %>
</p>
<p>
<strong>Status:</strong>
  <%= @account.status %>
</p>
<p>
<strong>AccountNumber:</strong>
  <%= @account.account_no %>
</p>
</div>
</div>
    </div>
    </div>
    </div>
    </div>
<center>
     <%= link_to 'Back', accounts_path %>
</center>
<br>